### ISSUE TITLE
new issues component

### ISSUE THREAD

**Issue by itsgivingchaotica** [hafeefas/Gitnalysis_FE#41]

**Comment by itsgivingchaotica** [comment]
<img width="144" alt="Screen Shot 2023-08-15 at 4 46 10 PM" src="https://github.com/hafeefas/Gitnalysis_FE/assets/91578619/0cecc177-3358-443d-860b-35b2873c3e72">

**Comment by itsgivingchaotica** [comment]
issues/:owner/:repo/count/getNum <- extract from this endpoint -> check the json response
<img width="329" alt="Screen Shot 2023-08-15 at 4 55 38 PM" src="https://github.com/hafeefas/Gitnalysis_FE/assets/91578619/7db0fed7-5280-42f8-8764-eed0024f3345">

**Comment by hafeefas** [comment]
Added the numOpen and numClosed for now, is returning the correct number 
<img width="196" alt="image" src="https://github.com/hafeefas/Gitnalysis_FE/assets/99234946/4759f6f5-95d4-4285-9cf8-ca9183839929">
